version: '3.1'

services:

  insap-web:
    build: ./docker/web
    env_file:
      - .env
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${WEB_ROOT_PATH}:/var/www/html/
    ports:
      - ${WEB_PORT}:80
    working_dir: ${WEB_WORKING_DIR}
    links:
      - insap-mysql
      - insap-mongo

  insap-mysql:
    image: library/mysql:8.0
    container_name: "insap_mysql"
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  insap-mongo:
    image: mongo:4.0-xenial
    container_name: "insap_mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_NAME: ${MONGO_DB_DATABASE}
      MONGO_DB_USER: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - ${MONGO_DB_PORT}:27017
    volumes:
      - ${MONGO_PATH}:/data/db

  insap-mongo-express:
    image: mongo-express
    links:
      - insap-mongo
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: "insap_mongo"

# To use, need PHP >= 8.0
#  insap-composer:
#    image: composer:2.0.13
#    volumes:
#      - ${WEB_ROOT_PATH}:/var/www/html/
#    working_dir: ${WEB_WORKING_DIR}
#    command: composer update --ignore-platform-reqs

  insap-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8002:80
    environment:
      - VIRTUAL_HOST=phpmyadmin.local
      - PMA_ARBITRARY=1
      - PMA_HOST=insap-mysql
      - PMA_USER=${MYSQL_ROOT_USERNAME}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}

