<?php

namespace Tests;

use App\Models\UserInfo;
use App\Modules\Plugins\Models\Plugin;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Laravel\Telescope\Telescope;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use withFaker;

    private $mongoDbSession = null;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->clearFileDir();
        Telescope::stopRecording();

        $this->mongoDbSession = DB::connection('mongodb_test')->getMongoClient()->startSession();
        $this->mongoDbSession->startTransaction();
        DB::beginTransaction();
    }

    protected function tearDown(): void
    {
        DB::rollBack();
        $this->mongoDbSession->abortTransaction();
        parent::tearDown();
    }

    private function clearFileDir() {
        $storage = Storage::disk('fileStore');
        $storage->delete($storage->allFiles());

        $storage = Storage::disk('process');
        foreach ($storage->allDirectories() as $directory) {
            $storage->deleteDirectory($directory);
        }
    }

    private function clearUserInfos() {
        UserInfo::query()->delete();
    }
}
