<?php

namespace Tests;

use App\Models\UserInfo;
use App\Modules\Plugins\Models\Plugin;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Storage;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->clearFileDir();
        $this->clearUserInfos();

        Artisan::call('migrate:plugin', ['slug' => Plugin::TEST_PLUGIN_SLUG]);
        $this->seed();
    }

    private function clearFileDir() {
        $storage = Storage::disk('fileStore');
        $storage->delete($storage->allFiles());

        $storage = Storage::disk('import');
        foreach ($storage->allDirectories() as $directory) {
            $storage->deleteDirectory($directory);
        }
    }

    private function clearUserInfos() {
        UserInfo::query()->delete();
    }
}
