global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'stats'
    honor_labels: true
    static_configs:
      - targets: ['insap-node-exporter:9100']
  - job_name: 'mysql'
    honor_labels: true
    static_configs:
      - targets: ['insap-mysql-exporter:9104']
  - job_name: 'mongodb'
    honor_labels: true
    static_configs:
      - targets: ['insap-mongo-exporter:9091']
