<?php


use App\Enums\Process\ProcessType;
use App\Modules\Processing\Factories\ProcessTypeFactory;
use App\Modules\Processing\Services\ProcessAppService;
use App\Modules\Processing\Services\ProcessServiceInterface;
use App\Modules\Project\Services\RecordService;
use Illuminate\Contracts\Container\BindingResolutionException;
use Tests\Fixture\ApplianceFixture;
use Tests\Fixture\ProcessFixture;
use Tests\Fixture\ProjectFixture;
use Tests\Fixture\RecordFixture;

class AdcpTest extends \Tests\TestCase
{
    private ?ProcessAppService $processAppService = null;
    private ?RecordService $recordService = null;

    private ?ProcessServiceInterface $importerService = null;
    private ?ProcessServiceInterface $exporterService = null;

    private ?ProjectFixture $projectFixture = null;
    private ?ApplianceFixture $applianceFixture = null;
    private ?ProcessFixture $processFixture = null;
    private ?RecordFixture $recordFixture;

    /**
     * @throws BindingResolutionException
     */
    public function setUp(): void
    {
        parent::setUp();

        $this->processAppService = $this->app->make(ProcessAppService::class);
        $this->recordService = $this->app->make(RecordService::class);

        $this->importerService = $this->app->make(ProcessTypeFactory::class)->create(ProcessType::create(ProcessType::IMPORTER));
        $this->exporterService = $this->app->make(ProcessTypeFactory::class)->create(ProcessType::create(ProcessType::EXPORTER));

        $this->projectFixture = $this->app->make(ProjectFixture::class);
        $this->applianceFixture = $this->app->make(ApplianceFixture::class);
        $this->processFixture = $this->app->make(ProcessFixture::class);
        $this->recordFixture = $this->app->make(RecordFixture::class);

    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $this->processAppService = null;
        $this->recordService = null;

        $this->importerService = null;
        $this->exporterService = null;

        $this->projectFixture = null;
        $this->applianceFixture = null;
        $this->processFixture = null;
        $this->recordFixture = null;
    }

    public function testBasic(): void
    {

    }
}
