<?php

namespace Tests\Unit;

use App\Enums\ActiveStatus;
use App\Models\User;
use App\Modules\Project\Models\Record;
use App\Modules\Project\Models\RecordData;
use App\Modules\Project\Services\RecordService;
use Tests\TestCase;

class RecordTest extends TestCase
{
    private ?User $user;

    private ?Record $record;
    private ?RecordService $recordService;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::find(User::TEST_USER_ID);
        $this->record = Record::find(Record::TEST_RECORD_ID);
        $this->recordService = $this->app->make(RecordService::class);
    }

    public function testCreate() {
        $array = [
            'name' => 'TestTest',
            'description' => 'test',
        ];

        $recordData = RecordData::find(RecordData::TEST_RECORD_DATA_ID);
        $this->record = $this->recordService->create($array, $recordData, $this->user);

        $this->assertTrue( $this->record instanceof Record);
        $this->assertNotEmpty($this->record);

        $this->assertEquals($array['name'], $this->record->name);
        $this->assertEquals($array['description'], $this->record->description);
        $this->assertEquals(ActiveStatus::ACTIVE, $this->record->is_active);
    }

    public function testDelete() {
        $id = $this->record->id;
        // Delete
        $this->recordService->delete($this->record);

        $this->assertNull(Record::find($id));
    }
}
